#!/bin/bash

set -eu

cd "$(dirname "${0}")/../"

BUNDLE_ID="me.villani.lorenzo.TurboBoostControl"
KEXT_FILE="TurboBoostControl.kext"

DEST_DIR="/Library/Extensions"
DEST_PATH="${DEST_DIR}/${KEXT_FILE}"

# Cleanup
sudo kextunload -b "${BUNDLE_ID}" || true
sudo rm -rf "${DEST_PATH}"

# Stage
sudo cp -r \
    "${HOME}/Library/Developer/Xcode/DerivedData/"TurboBoostControl*"/Build/Products/Debug/${KEXT_FILE}" \
    "${DEST_DIR}"
sudo chown -R root:wheel "${DEST_PATH}"

# Check
sudo kextlibs -xml "${DEST_PATH}"
sudo kextutil -n -t "${DEST_PATH}"

# Load
sudo kextload "${DEST_PATH}"
